### ISSUE TITLE
When I export a site, it only exports the HTML and not the CSS

### ISSUE THREAD

**Issue by gorkem-bwl** [chaibuilder/sdk#35]
Just like the title - When I export a site, it only exports the HTML and not the CSS. I need the corresponding CSS files to make sure the exported HTML file shows.

How can I do that?

**Comment by surajair** [comment]
we currently only provide HTML as part of export code. We will provide a way to download entire page with a single click instead of copying the code in upcoming versions.

**Comment by gorkem-bwl** [comment]
The new version (v0.1.16 - beta) works without an issue - I was able to download the zip file that comes with the corresponding CSS.

**Comment by surajair** [comment]
closing this issue
